version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fintrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fintrack_db
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: finpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintrack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finuser -d fintrack_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
    command: [ "postgres", "-c", "listen_addresses=*" ]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fintrack-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fintrack.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fintrack-network
    depends_on:
      postgres:
        condition: service_healthy

  fintrack-api:
    build: .
    container_name: fintrack-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
#      JWT_SECRET_FILE: /run/secrets/jwt_secret
#    secrets:
#      - jwt_secret
    networks:
      fintrack-network:
        aliases:
          - postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  fintrack-network:
    driver: bridge